# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  /*
    boot.kernelPackages =  let
        pinnedNixPkgs = import (pkgs.fetchFromGitHub {
            owner = "nixos";
            repo = "nixpkgs";
            rev = "f74c64bacf35f0be2c781de68afc2c84a8c54ea1";
            hash = "sha256-FKSlfAc9IUQ3BqiETWaVV0ONqeArQihIEnRH3v9rcwg=";
        }) {};
        myKernel = pinnedNixPkgs.linux_6_17;
        in pkgs.recurseIntoAttrs (pinnedNixPkgs.linuxPackagesFor myKernel);
  */
  boot.kernelPackages = pkgs.linuxPackages_latest;
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "thunderbolt"
    "mptsas"
    "mpt3sas"
    "sg"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [
    "amdgpu"
    "nct6775"
  ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  #boot.blacklistedKernelModules = [ ];

  #Swap
  /*
    swapDevices = [{
      device = "/dev/nvme0n1p6";
      randomEncryption.enable = true;
    }];
  */

  #LTFS
  boot.kernelPatches = [
    {
      name = "enable-scsi-proc-fs";
      patch = null; # No actual patch file is needed, just the config
      extraConfig = ''
        SCSI_PROC_FS y
      '';
    }
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/4feaab09-e6e9-4631-8c3e-acd7c85790a3";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/39DF-018A";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;
  networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp11s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  # Tina's edits
  # Fixing Model M / No super key
  environment.etc."libinput/local-overrides.quirks".text = ''
    [Serial Keyboards]
    MatchUdevType=keyboard
    MatchName=keyd virtual keyboard
    AttrKeyboardIntegration=internal
  '';
  services.keyd = {
    enable = true;
    keyboards = {
      default = {
        ids = [ "*" ];
        settings = {
          main = {
            rightcontrol = "leftmeta";
          };
          otherlayer = { };
        };
        extraConfig = ''
          # put here any extra-config, e.g. you can copy/paste here directly a configuration, just remove the ids part
        '';
      };
    };
  };

  #AMD Plafrom stuff
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  #CPU monitoring
  #hardware.cpu.amd.ryzen-smu.enable = true;

  #Hardware specific packages
  programs.coolercontrol.enable = true;
  programs.corectrl.enable = true;
  environment.systemPackages = with pkgs; [
    lm_sensors
    liquidctl # Corsair monitoring and settings
    pciutils
    hwloc
    usbutils
    mesa
    mesa-demos
    vulkan-tools
    (btop.override { rocmSupport = true; })
    rocmPackages.rocm-smi
    #openrgb-with-all-plugins
    #(pkgs.callPackage inputs.nixpkgs-hyprgirl { }).ryzen-monitor-ng
  ];
  #Hardware specific services
  #services.cpupower-gui.enable = true;
  services.hardware.openrgb.enable = true;

  #GPU drivers (6800xt)
  services.xserver.videoDrivers = [ "amdgpu" ];
  hardware.amdgpu.opencl.enable = true;

  #Bluetooth drivers (Asus proarts have that on board)
  hardware.bluetooth.enable = true;

}
